ignore:
  - vulnerability: CVE-2023-47038
  - vulnerability: CVE-2023-5981

  # example to ignore a vulnerability
  # This is the full set of supported rule fields:
  # - vulnerability: CVE-2008-4318
  #   fix-state: unknown
  #   package:
  #     name: libcurl
  #     version: 1.5.1
  #     type: npm
  #     location: "/usr/local/lib/node_modules/**"
